# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/UART/uart_top/uart_top.cache/wt [current_project]
set_property parent.project_path D:/UART/uart_top/uart_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/UART/uart_top/uart_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/UART/uart/uart_tx_f.vhdl
  D:/UART/uart/uart_rx_f.vhdl
  D:/UART/uart/uart_top.vhdl
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/UART/uart_top/uart_top.srcs/constrs_1/new/uart_top.xdc
set_property used_in_implementation false [get_files D:/UART/uart_top/uart_top.srcs/constrs_1/new/uart_top.xdc]


synth_design -top uart_top -part xc7z020clg484-1


write_checkpoint -force -noxdef uart_top.dcp

catch { report_utilization -file uart_top_utilization_synth.rpt -pb uart_top_utilization_synth.pb }
